name: Latest Results

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install GCC
      run: sudo apt-get install gcc

    - name: Build
      run: ./scripts/compile.sh
    
    - name: Compare Results
      run: ./scripts/compare.sh
    
    - name: Test Performance
      run: ./scripts/test.sh